name: Verify KSP2 Mod
description: 'Streamline the verification process for your KSP 2 mods.'
author: 'Sinon'

on:
  push:

jobs:
  version_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
