name: SpaceWarp Version Checker
description: 'Provides error checking for the version_check variable in Space Warp mods.'
author: 'Sinon'

icon: check-square
color: purple

runs: 
  using: composite
  steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Create Scripts Directory
        shell: bash
        run: |
          mkdir .github/scripts

      - name: Download verify_check.py
        shell: bash
        run: |
          curl -o ".github/scripts/verify_check.py" "https://vortan.dev/ksp/spacewarp/verify_check.py"

      - name: Install Requests
        shell: bash
        run: |
          python3 -m pip install requests

      - name: Run Verification
        shell: bash
        run: |
          python3 .github/scripts/verify_check.py
